services:
    _defaults:
        autowire: true
        public: false

    RatingBundle\Form\RatingType:
        tags:
            - { name: form.type, alias: rating }
        public: true

    RatingBundle\EventSubscriber\VoteSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    RatingBundle\Repository\RatingRepository:
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['RatingBundle\Model\AbstractRating']
        public: true

    RatingBundle\Repository\VoteRepository:
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['RatingBundle\Model\AbstractVote']
        public: true
